# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f4b4bd11e584168c07f0a8b541fb886f6de170fbc1ab241d061a05c02bc74a6bd6ab553395b2b4e9eb7cc401a20b46a4ff1c98e2ba76a37ed725f90c83c24fe

test:
  secret_key_base: 05443418e51aace40da90aa3cca8c2decc0514b7fb2f1cccec5feb8b6160603b412f6062b971d9ee5842ad91a5e7b74dac95633245ef0ccf868e48196aabb074

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
